# SPDX-FileCopyrightText: 2023 Oscar Bender-Stone <oscarbenderstone@gmail.com>
# SPDX-License-Identifier: Apache-2.0-WITH-LLVM-exception
start: term

term: graph | connection | ident | STRING
graph: ident? "{" term "}"
connection: term connector term
connector: edge | arrow
edge: "--"
arrow: "->"
ident: WORD

%import common.WORD
%import common.ESCAPED_STRING -> STRING
%import common.WS
%ignore WS
